### ISSUE TITLE
No value on declarations

### ISSUE THREAD

**Issue by rahmaniali-ir** [deno-front-end/css-parser#5]
Hi. I need to parse some css for a small project of mine, and "css-parser" is just what I needed. but there's a problem, the parsed declarations have "type" and "name" properties, but no "value". like this:
`declarations: [ { type: "property", name: "height" }, { type: "property", name: "margin" } ]`
It would be really awesome if you could help me. thanks.

**Comment by littledivy** [comment]
@rahmaniali-ir I just merged #4. Can you try if the `main` branch works for you now?

**Comment by rahmaniali-ir** [comment]
Yeah, it works perfectly now. thanks, @littledivy 🙏

**Comment by timonson** [comment]
There is still no `value` property on the `declarations`. What am I missing here?

```typescript
let ast = parse("p { color:yellow; --colorBlue: blue }")

// declarations: [ { type: "property", name: "color" }, { type: "property", name: "--colorBlue" } ]

**Comment by timonson** [comment]
@rahmaniali-ir 
@littledivy
